/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::PinnedAssetImage Water;
extern const Sifteo::PinnedAssetImage Dirt;
extern const Sifteo::PinnedAssetImage Grass;
extern const Sifteo::PinnedAssetImage GrassDark;
extern const Sifteo::PinnedAssetImage Rocks;
extern const Sifteo::PinnedAssetImage Font;
extern const Sifteo::AssetTracker Music;
