/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage Dirt;
extern const Sifteo::AssetImage GrassDark;
extern const Sifteo::AssetImage Rocks;
extern const Sifteo::AssetImage GrassLight;
extern const Sifteo::AssetImage ChestOpen;
extern const Sifteo::AssetImage Sand;
extern const Sifteo::AssetImage Water;
extern const Sifteo::AssetImage Boulder;
extern const Sifteo::AssetImage ChestClosed;
extern const Sifteo::AssetImage FlowerRed;
extern const Sifteo::AssetImage FlowerBlue;
extern const Sifteo::AssetImage Key;
extern const Sifteo::PinnedAssetImage Emptiness;
extern const Sifteo::PinnedAssetImage Font;
